🚀  update dockerfile front
fullstacktf/ControlHorarios-Frontend pull request #13
Opened 2020-10-30 13:26 UTC by jaimerperez

@yodra @ManzDev

2020-10-30 19:46 UTC, yodra requested changes

2020-10-30 19:46 UTC, yodra commented on Dockerfile
> +#ENTRYPOINT ["bash", "./run.sh"]
Los comentarios mejor eliminarlos siempre, si necesitamos recuperarlo siempre podemos recurrir al histórico del repo

2020-10-30 19:46 UTC, yodra commented on run.sh
>  npm run stylelint
Yo esto normalmente lo prefiro configurar para que se lance antes de un commit. Utilizando un hook `pre-commit` para que antes de hacer un commit se lance el linter o se verifique que cumple todo lo que esperamos.
De este modo me aseguró de que el código siempre siga el mismo estiló. 👌

2020-10-30 19:46 UTC, yodra commented on Dockerfile
>  CMD ["nginx", "-g", "daemon  off;"]
Para evitar el error que indica aquí revisen https://editorconfig.org/ con estoy te añade la última línea necesaria

2020-11-10 13:22 UTC, AiranSchez submitted a review, later dismissed

2020-11-10 13:23 UTC, Pandacore submitted a review, later dismissed

2020-11-10 13:25 UTC, AiranSchez commented on Dockerfile
>  CMD ["nginx", "-g", "daemon  off;"]
Buenas! Hemos estado revisando editorconfig y lo tendremos en cuenta para futuras ocasiones. Por el momento con la línea 10 nos funciona todo perfecto y no sabemos si debemos usar esta herramienta por ahora.

2020-11-11 08:58 UTC, yodra commented on Dockerfile
>  CMD ["nginx", "-g", "daemon  off;"]
Se usa mucho en los proyectos, para evitar algunos problemas de formato de fin de línea, cuando trabajamos con equipos en Windows y Unix. O para que todos los ficheros mantengan el `endcoding`. Por ello github ya te avisa que algo va mal y todo este tipo de cosas suele dar muchos problemas.

2020-11-11 13:23 UTC, Pandacore commented on Dockerfile
>  CMD ["nginx", "-g", "daemon  off;"]
Ya añadimos .editorconfig al proyecto y lo mergeamos desde consola. Muchas gracias.

2020-11-11 13:23 UTC, closed without merging